### ISSUE TITLE
RC3 issue to launch

### ISSUE THREAD

**Issue by k4nfr3** [MartinDrab/IRPMon#102]
Hi,

i've used the old version and had success.
I'm a beginner so please excuse stupid questions.
IRPMmon version of 2017 works fine.
I'm now trying to used you latest version RC3.
But when I run the gui I get this

![image](https://user-images.githubusercontent.com/45294916/122735374-44b00d00-d27f-11eb-97a1-2684626cbb4e.png)

How to know which port it's listening to ?

If I click ok, I get in the Gui, but cannot select any drivers.
In CmdLine I get the following error

C:\Program Files\IRPMon\x64>irpmonc --input=D:\\.\\IRPMon
[INFO]: 10 parsers loaded
[INFO]:   EAParser (version 1.0.0)
[INFO]:   Hexer (version 1.0.0)
[INFO]:   KbdClass (version 1.0.0)
[INFO]:   PipesParser (version 1.0.0)
[INFO]:   MouClass (version 1.0.0)
[INFO]:   PipesParser (version 1.0.0)
[INFO]:   PnPDevCaps (version 1.0.0)
[INFO]:   PnPIDs (version 1.0.0)
[INFO]:   PnPInterface (version 1.0.0)
[INFO]:   SecDescs (version 1.0.0)
[INFO]:
[ERROR]: Unable to initialize IRPMon library: 2

My environment in a VM of Win10 x64 1903, running on a ESX host.

Regards

**Comment by tormodvolden** [comment]
If you are not doing remote monitoring you should not use the network option. Instead IRPMon should connect directly to the driver.

If you don't have a "Device" tab between "None" and "Network" it can be because you haven't started IPRMon with administrative rights.
