### ISSUE TITLE
Cannot load unsigned driver

### ISSUE THREAD

**Issue by TheOnlyRealTodd** [MartinDrab/IRPMon#11]
Is there any way to get a signed version of the irpmon driver? I cannot load this driver no matter what. I've tried both going into gpedit.msc and changing the driver install policy to IGNORE and I've also went into the boot screen with F8 on my Windows 7 and chosen the option to allow the installation of unsigned drivers. Strangely, when I launch IRPMon even after **both of those things are done**, it works for a few seconds then I get a dialog from Windows saying the driver is not signed and has been blocked. :(

**Comment by MartinDrab** [comment]
Windows actually shows you the "unsigned driver" dialog even when the unsigned driver successfully loads.  What error does IRPMon show?

The signed IRPMon driver should be part of the v0.8 release. Did you use the released version, or compiled the driver from the sources?

**Comment by TheOnlyRealTodd** [comment]
Yes sir, it shows the unsigned dialog after the unsigned driver first loads because the loading box has the green success message for a split second then IRPMon launches, but doesn't actually capture anything (even if I set it up to monitor x driver for example) and then 10 seconds after, I get this:
![irpmon-sig](https://user-images.githubusercontent.com/19983799/33522089-b320d6ec-d798-11e7-80f4-25bd131f53ac.png)
Also shown that I set to ignore this warning. Also this was after I did the boot-screen allowance of unsigned drivers ¯\_(ツ)_/¯

However, there may be hope, I just need to get ahold of the signed driver if you have it available at a link. I just successfully used several other programs with signed drivers so it's definitely not just the OS. I used the binaries from this repo (did not build myself but used binaries in the bin folder). Thank you for your help!!!

**Comment by MartinDrab** [comment]
Hello,

I recommend to use the v0.8 release binaries
https://github.com/MartinDrab/IRPMon/releases/download/0.8/IRPMon.v0.8.zip

 * they are signed by my certificate (non-EV, so the signature is not good enough for clean Windows 10 post-Anniversary with Secure Boot),
 * the binaries were tested.

The binaires folder in the repository may contain binaries that have some additional (and not tested too much) changes. They are not signed and their main purpose is to be used by those who do not have some of the tools required for the project compilation (e.g. Delphi XE2 and older).

Also, to persuade IRPMon for event capturing, you need to do several steps:
 * check the Capture events item in the Monitoring menu,
 * select the driver and/or devices to be monitored. For example, you may choose Action -> Select drivers / devices, find the target driver(s) and check the Hook item in their context menu. Particularly, if you wish to monitor device-specific events, such as IRPs and their completion, you need to check the Hook item in their context menu (there are some other possibilities but this is the basic one).

Than, IRPMon should see the events.

**Comment by TheOnlyRealTodd** [comment]
Got it working, thanks so much for that!!
