### ISSUE TITLE
Log data associated with the requests

### ISSUE THREAD

**Issue by MartinDrab** [MartinDrab/IRPMon#13]
The logged data should be interpreted by the IRPMon GUI application. Also, there should be something like a threshold in order not to waste all available memory by logging large read/write requests.

**Comment by r3verser** [comment]
This feature will be great!

**Comment by MartinDrab** [comment]
Hello,

I hope to finish the implementation in mid-November. The only thing remaining is a general interface for data parsers/visualisers. Currently, the associated data are shown in hex.

**Comment by MartinDrab** [comment]
Well, I added basic support for logging data associated with some types of requests. Also, it is now possible to write custom data parsers. The thing, however, needs some small additional work but should be finished quite quickly.

**Comment by robomotic** [comment]
Amazing are you going to put that in the next 0.9 release?

**Comment by MartinDrab** [comment]
> Amazing are you going to put that in the next 0.9 release?

Logging data associated with individual requests will be part of the release. Also, a "custom" data parser called Hexer (which displays the data in hex) will be here. 

I probably won't be able to create some additional parsers though. However, Hexer's source code should give you hints how to write our own. Maybe, I will add one very simple parser to make things absolutely clear.
