### ISSUE TITLE
Install Failed in Windows 10 x64.

### ISSUE THREAD

**Issue by d0gkiller87** [MartinDrab/IRPMon#15]
![irl](https://user-images.githubusercontent.com/32069685/45600100-a46f8e80-ba29-11e8-8d2a-7650c898fcb7.PNG)
Can't install through Admin Command-Line.

**Comment by MartinDrab** [comment]
Hello,

irpmonconsole is deprecated for some time. If you wish to use binaries, please take the v0.8 release.

The 1073 error code menas that the IRPMon driver service is already present. You may get rid of it by invoking `irpmonconsole --uninstall`.

**Comment by d0gkiller87** [comment]
Hi, Thanks for reply. Even using IRPMon, it can't create a services or load the driver. The error code is 1072 and 1058, which are about drivers and services error.

**Comment by MartinDrab** [comment]
1072 should disappear after a reboot. Sometimes, a service entry cannot be deleted immediately and a reboot is required to complete it.

**Comment by d0gkiller87** [comment]
Sure. I’ll take look after a reboot. Sorry I’m busy now. I’ll check it later.

**Comment by d0gkiller87** [comment]
Problem solved by reboot. Thanks for help.
