### ISSUE TITLE
Working under Windows 10?

### ISSUE THREAD

**Issue by dakami** [MartinDrab/IRPMon#2]
From a Windows Admin prompt:

C:\cygwin64\home\dan\IRPMon\binaries>irpmonconsole.exe --uninstall
SUCCESS

C:\cygwin64\home\dan\IRPMon\binaries>irpmonconsole.exe --install
ERROR StartService(): 577

C:\cygwin64\home\dan\IRPMon\binaries>irpmonconsole.exe
ERROR: Failed to initialize the irpmndrv.dll library: 2

hmmmm?

**Comment by MartinDrab** [comment]
Is this a 32-bit or 64-bit version of Windows?

Did you (test)signed the driver? The 577 error code stands for ERROR_INVALID_IMAGE_HASH which usually means that Windows cannot verify digital signature of a binary (driver) (see net helpmsg 577).
