### ISSUE TITLE
No binaries

### ISSUE THREAD

**Issue by aamcampbell** [MartinDrab/IRPMon#3]
The README.md file says, "If you cannot or do not want to compile the project yourself, use the binaries in the <code>binaries</code>." However, there isn't any binaries folder, nor do I see any precompiled binaries in this repository.

**Comment by aamcampbell** [comment]
Looks like the binaries were removed in commit 706b4799a393.

**Comment by MartinDrab** [comment]
Hello,

thank you for pointing this out. I removed the binaries by accident. I have just added the directory into the repository.

**Comment by MartinDrab** [comment]
I've includes necessary data files (translation tables for IOTLC, NTSTATUS and Win32 error values), so the thing now should really (and finally) work.
