### ISSUE TITLE
after select driver program`s windows is clear

### ISSUE THREAD

**Issue by xSanx** [MartinDrab/IRPMon#75]
Hi, again the question ... I started the program, went into Action -> Select drivers/devices....  selected Device/KeyboardClass0 and clicked ok. The window is empty ....

**Comment by MartinDrab** [comment]
* Did you checked the **Hook** item in the context menu when selecting the device?
* Did you checked **Capture events** in the **Monitoring** menu?
* How many keyboards do you have connected to your machine? For example, laptop keyboards are usually referenced as PS/2 and represented by the KeyboardClass0 device, additional keyboards are KeyboardClass1 etc. (USB ones). In other words, you need to use the right keyboard to see the events (num lock, caps lock and scroll lock are exceptions).

**Comment by xSanx** [comment]
seems to figure it out ... Great tool, but how do you know which irp is sent to the driver, and which irp sends the driver in response? Thanks

**Comment by MartinDrab** [comment]
Basically, my driver just hooks IRP handlers of the target driver. Hence, it gets control when an IRP is sent to the device. For each IRP, the driver also registers a completion routine, so it gets notified when the IRP gets completed.

**Comment by xSanx** [comment]
super, but how can I see what the driver returned?

**Comment by MartinDrab** [comment]
Look into the **IOSB Status** column of the IRP completion. Or into the **Result** column of the IRP (if it is STATUS_PENDING (0x103), you still need to look at the IOSB Status of the corresponding IRP completion event).

**Comment by xSanx** [comment]
mean all the packages STATUS_PENDING(0x103) from the driver? no others?

**Comment by MartinDrab** [comment]
Well, the keyboard events (key press and release) are processed in the following manner:
* an IRP_MJ_READ is sent to each KeyboardClassX device,
* kbdclass.sys pends the IRP (thus, STATUS_PENDING) and stores it in its internal queue,
* when a keyboard event occurrs, one read IRP is removed from that internal queue and completed (IOSB Status and IOSB Information is set).

Caps lock, num lock and scroll lock should produce also an IOCTL setting the keyboard LEDs which AFAIK is not pended by the driver. 

So, look at **IOSB Status** and **IOSB Information** columns in rows representing IRP completions.

**Comment by xSanx** [comment]
Yes, I already experimented with the keyboard. Is Status_pending set after processing by any driver? If for example, is it a software driver of some kind of antivirus?

**Comment by MartinDrab** [comment]
> Is Status_pending set after processing by any driver?

No. If the driver processes the IRP synchronously (e.g. directly in its dispatch handler, no queuing), it must
* set IOSB Status and Information to report the result,
* return the NTSTATUS value set to IOSB Status.

Many drivers do process IRPs synchronously. But all depends on the driver author. Also, there are some IRP types that AFAIK must be processed synchronously (the driver MUST NOT return STATUS_PENDING). IRP_MJ_CREATE is one of them.

**Comment by xSanx** [comment]
I have fields where IOSB is 0x00000000 and there is where IOSB is 0x0000000000002 or 0x000000000012. IOSB status everywhere is STATUC_SUCCESS, 
Is this the driver’s response?

**Comment by MartinDrab** [comment]
IOSB is a shortcut for **I/O Status Block** which contains the following information
* a status code reporting whether the IRP was completed successfully or an error occurred,
* an*Information* field meaning ofwhich depends on the IRP type – for example, drivers use it to signal number of bytes read.

So,you must be careful to distinguish between these two fields. As far as I know, the keyboard class driver usually completes its IRPs with `STATUS_SUCCESS` (0).

Driver responses are reported as events of type **IRP Comp**.

I have also improved (quite greatly I think) my tutorial about keyboard monitoring. Hope you find it helpful.
https://github.com/MartinDrab/IRPMon/wiki/KeyboardMonitoring

The Wiki also contains some additional information about Windows drivers in general which may also provide some insight.

I am not sure whether I answered your question. If not, please try asking again.

**Comment by xSanx** [comment]
thank you for help . I work with you program, this is great program.
